[profile.default]
src = "src"
out = "out"
test = 'test'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
"@uniswap-v2-core" = "1.0.1"
"@uniswap-v2-periphery" = "1.1.0-beta.0"

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"
bnb_test = "${BNB_TEST_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
localhost = { key = "" , url="http://127.0.0.1:8545"}
bnbTestnet = { key = "${BNB_TEST_ETHERSCAN_API_KEY}", url = "${BNB_TEST_ETHERSCAN_API_URL}", chain=8453 }
