[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_fun = "8P7D8TFQqcpTpuejoGQugjD68aKEimG2d3BL15SUnDdW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[test]
upgradeable = true

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/createToken.test.ts"
